# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshm" do
  version "1.0.14"

  on_macos do
    on_intel do
      sha256 "60fed76aee5d418f65122f7304da09ab25d1bdd6023086f678ed5bc0f031feef"
      url "https://github.com/krabiworld/sshm/releases/download/v#{version}/sshm_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "38afd037842d99580ce64f654e9338d7ec2fa58385bff9ca52e8c04df8b2450e"
      url "https://github.com/krabiworld/sshm/releases/download/v#{version}/sshm_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "138c2a4b485bdbc1f0a177f7b5e0c97e8e4d8d63bd7d77a0575b8c6af14c52cd"
      url "https://github.com/krabiworld/sshm/releases/download/v#{version}/sshm_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f72f28f056ad45336c97e487dcfeed1ffeb836c3d0aecd0499d76b9f140ffa8c"
      url "https://github.com/krabiworld/sshm/releases/download/v#{version}/sshm_linux_arm64.tar.gz"
    end
  end

  name "sshm"
  desc ""
  homepage "https://github.com/krabiworld/sshm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshm"

  # No zap stanza required

end
