# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshm" do
  version "1.0.13"

  on_macos do
    on_intel do
      sha256 "ba42568e95df562044487f0ee1080ccfa14a750d8ffc513038d940ebe45fea7c"
      url "https://github.com/krabiworld/sshm/releases/download/v#{version}/sshm_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3ee8942f76f45df3b3ad83ab51e69018bfaf883857be46ec237ec2314bfc818e"
      url "https://github.com/krabiworld/sshm/releases/download/v#{version}/sshm_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1ac314676726ef02eb78e4ec75f8eabe59c481c6c18f3ef2123dc11b42e729e4"
      url "https://github.com/krabiworld/sshm/releases/download/v#{version}/sshm_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "41656ada61c08948927a4d12bc14fafd0a3b8be517caff2e5b08041db74ecf61"
      url "https://github.com/krabiworld/sshm/releases/download/v#{version}/sshm_linux_arm64.tar.gz"
    end
  end

  name "sshm"
  desc ""
  homepage "https://github.com/krabiworld/sshm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshm"

  # No zap stanza required

end
