# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshm" do
  version "1.0.13"

  on_macos do
    on_intel do
      sha256 "94fe5ac653d56e36c10a1791cccbd5416104ac2b3f36b73a9c5afdb4069b80e7"
      url "https://github.com/krabiworld/sshm/releases/download/v#{version}/sshm_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6b0ec84bd5aa7dd7f7894764ee312eff030fa123d8b5d6e12d770abf394d97f"
      url "https://github.com/krabiworld/sshm/releases/download/v#{version}/sshm_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b5f362e1c63677731f643e0f5df17a93cad7e81fe088aa22683f666661d244f"
      url "https://github.com/krabiworld/sshm/releases/download/v#{version}/sshm_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5711f7662051e231a91e215c9a93ed8ff874a3f07602444b3c2c3e0893650f07"
      url "https://github.com/krabiworld/sshm/releases/download/v#{version}/sshm_linux_arm64.tar.gz"
    end
  end

  name "sshm"
  desc ""
  homepage "https://github.com/krabiworld/sshm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshm"

  # No zap stanza required

end
